repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "mypy.ini"]
        language: system
        files: ^src/|^tests/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            \.vscode/.*|
            \.devcontainer/.*|
            pyrightconfig\.json|
            .*\.egg-info/.*|
            Makefile.*
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            \.vscode/.*|
            \.devcontainer/.*|
            pyrightconfig\.json|
            .*\.egg-info/.*|
            Makefile.*
          )$
