---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - fastapi
          - httpx
          - typing-extensions
        files: ^src/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            \.vscode/.*|
            \.devcontainer/.*|
            pyrightconfig\.json|
            .*\.egg-info/.*|
            Makefile.*
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            \.vscode/.*|
            \.devcontainer/.*|
            pyrightconfig\.json|
            .*\.egg-info/.*|
            Makefile.*
          )$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
