target-version = "py312"
line-length = 100
[lint]
select = ["E", "F", "W", "N", "I", "C90"]
ignore = ["E501"] # Disable line-too-long
[lint.isort]
known-first-party = ["ai_gateway"]
combine-as-imports = true
force-single-line = false
