name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install uv
      - name: Install uv
        run: |
          pipx install uv
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      - name: Install deps
        run: |
          uv pip install --system -r pyproject.toml
      - name: Lint (ruff)
        run: uv pip run ruff .
      - name: Type check (mypy)
        run: uv pip run mypy src
      - name: Tests
        run: uv pip run pytest --cov=src --cov-report=term-missing --cov-fail-under=85
