---
name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set package version in __init__.py
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}"
          sed -i \
            "s/^__version__ = .*/__version__ = \"${VERSION}\"/" \
            src/ai_gateway/__init__.py

      - name: Set version in pyproject.toml
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}"
          sed -i \
            "s/^version = \".*\"/version = \"${VERSION}\"/" \
            pyproject.toml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install uv
      - name: Install uv
        run: |
          pipx install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (ruff)
        run: ruff format --check .

      - name: Type check (mypy)
        run: mypy src

      - name: Tests
        run: pytest --cov=src --cov-report=term-missing --cov-fail-under=85
